// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucnasxinqweimswkzwgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbmFzeGlucXdlaW1zd2t6d2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDE0OTQsImV4cCI6MjA2NzU3NzQ5NH0.jdAwT10O1HID8HZ8q9RyILZfAjRIsJC39e2krYGth5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});